-- ============================
-- TABELA: planos
-- ============================
CREATE TABLE planos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    valor DECIMAL(19,2),
    duracao_meses INT
);

-- ============================
-- TABELA: matriculas
-- ============================
CREATE TABLE matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id BIGINT,
    data_vencimento DATE,
    esta_ativa BOOLEAN,
    CONSTRAINT fk_matricula_plano FOREIGN KEY (plano_id) REFERENCES planos(id)
);

-- ============================
-- TABELA: usuario
-- ============================
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    matricula_id BIGINT,
    CONSTRAINT fk_usuario_matricula FOREIGN KEY (matricula_id) REFERENCES matriculas(id)
);

-- ============================
-- TABELA: role
-- ============================
CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

-- ============================
-- TABELA: usuario_roles (tabela pivot Many-to-Many)
-- ============================
CREATE TABLE usuario_roles (
    usuario_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, role_id),
    CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_usuario_roles_role FOREIGN KEY (role_id) REFERENCES role(id)
);

-- ============================
-- TABELA: produto
-- ============================
CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    preco DECIMAL(19,2) NOT NULL,
    estoque INT NOT NULL,
    imagem_url TEXT
);

-- ============================
-- TABELA: equipamento
-- ============================
CREATE TABLE equipamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    quantidade INT,
    valor DECIMAL(19,2),
    data_aquisicao DATE
);
