-- ============================
-- TABELA: despesas
-- ============================
CREATE TABLE despesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) NOT NULL,
    valor DECIMAL(19, 2),
    data_vencimento DATE
);

-- ============================
-- TABELA: pedidos
-- ============================
CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    data_criacao DATE DEFAULT CURRENT_DATE,
    valor_total DECIMAL(19, 2),

    CONSTRAINT fk_pedido_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ============================
-- TABELA: mensalidades
-- ============================
CREATE TABLE mensalidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    valor_pago DECIMAL(19, 2),
    data_pagamento DATE,

    CONSTRAINT fk_mensalidade_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ============================
-- TABELA: item_pedido
-- ============================
CREATE TABLE item_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario DECIMAL(19, 2) NOT NULL,
    subtotal DECIMAL(19, 2) NOT NULL,

    CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
    CONSTRAINT fk_item_pedido_produto FOREIGN KEY (produto_id) REFERENCES produto(id)
);

-- Ainda tô terminando